### ISSUE TITLE
unknown attribute: password_salt because of :password_archivable.

### ISSUE THREAD

**Issue by ryanermita** [phatworx/devise_security_extension#150]
unknown attribute: password_salt because of :password_archivable.

Devise version 3.4.1
Rails version 4.0
devise_securiy_extension version 0.9.2

here's the bottom part of full trace:

actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in `call'
railties (4.1.8) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
puma (2.10.2) lib/puma/server.rb:492:in `handle_request'
puma (2.10.2) lib/puma/server.rb:363:in `process_client'
puma (2.10.2) lib/puma/server.rb:254:in `block in run'
puma (2.10.2) lib/puma/thread_pool.rb:101:in `call'
puma (2.10.2) lib/puma/thread_pool.rb:101:in `block in spawn_thread'

**Comment by ryanermita** [comment]
fixed by installing the latest version of devise_security_extension:

`gem 'devise_security_extension', github: 'phatworx/devise_security_extension'`
