### ISSUE TITLE
unknown attribute 'password_salt' for OldPassword

### ISSUE THREAD

**Issue by chrisvel** [phatworx/devise_security_extension#182]
I use devise 4.0.0 and I get this message when i try to create a new user:

# RAILS_ENV=development bundle exec rake db:seed 

```
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'password_salt' for OldPassword.
/home/deploy/app/db/seeds.rb:9:in `<top (required)>'
NoMethodError: undefined method `password_salt=' for #<OldPassword:0x000012ac697d78>
Did you mean?  password_archivable=
```

Any ideas what is related to ?

**Comment by atarantino** [comment]
Not exactly in your situation, but was getting same unknown attribute error.

Used this in my gemfile:
gem 'devise_security_extension', github: 'phatworx/devise_security_extension'

Updated the gem from 0.9.2 -> 0.10.0, but also downgraded Devise from 4.1 -> 3.5.9 (which kinda sucks). Fixed the error though.

**Comment by kevinhq** [comment]
Get same problem when changing password: 
```ruby
unknown attribute 'password_salt'
```

We used devise 4.1.1 with devise_security_extension 0.9.2. We don't want to downgrade devise, so my solution was modifying the migration for old_passwords table a little bit:

```ruby
create_table :old_passwords do |t|
      t.string :encrypted_password, :null => false
      t.string :password_archivable_type, :null => false
      t.integer :password_archivable_id, :null => false
      t.string :password_salt #added password_salt attributes to fix error.
      t.datetime :created_at
    end
    add_index :old_passwords, [:password_archivable_type, :password_archivable_id], :name => :index_password_archivable
```

**Comment by levi-l-damian** [comment]
I have the same problem, I am using devise 4.1.1 and devise_security_extension 0.9.2.
In my user.rb these are enabled: password_expirable, password_archivable, expirable.
The associated columns are created in the users table: password_changed_at, last_activity_at, expired_at.

The table old passwords is created as shown here:
###                                             Table "public.old_passwords"
          Column          |            Type             |                         Modifiers                          
--------------------------+-----------------------------+------------------------------------------------------------
 id                       | integer                     | not null default nextval('old_passwords_id_seq'::regclass)
 encrypted_password       | character varying           | not null
 password_archivable_type | character varying           | not null
 password_archivable_id   | integer                     | not null
 created_at               | timestamp without time zone | 
 password_salt            | character varying           | 
Indexes:
    "old_passwords_pkey" PRIMARY KEY, btree (id)
    "index_password_archivable" btree (password_archivable_type, password_archivable_id)

I added the column password_salt as kevinhq recommended.

The error I am getting is: 
NoMethodError in Devise::PasswordExpiredController#update
undefined method `<<' for #<ActiveRecord::AssociationRelation []>
        arel.public_send(method, *args, &block)
      else
        super
      end
    end
  end

activerecord (5.0.0) lib/active_record/relation/delegation.rb:123:in `method_missing'
activerecord (5.0.0) lib/active_record/relation/delegation.rb:93:in `method_missing'
devise_security_extension (0.9.2) lib/devise_security_extension/models/password_archivable.rb:30:in `password_archive_included?'
devise_security_extension (0.9.2) lib/devise_security_extension/models/password_archivable.rb:15:in `validate_password_archive'
activesupport (5.0.0) lib/active_support/callbacks.rb:382:in `block in make_lambda'

I am using Rails 5.0.0. and Ruby 2.3.1

Everything is working well when I am commenting out password_archivable in the model user.rb

I don't want to downgrade to devise 3.x
Please let us know a fix to this issue.

**Comment by c2wei** [comment]
Hi @levi-l-damian, the error you encountered is caused by line 29 in password_archivable.rb.

Apparently in Rails 5, you cannot inject an object into ActiveRelation class anymore. Therefore the quick but dirty fix is to convert the ActiveRelation class into an Array.

In line 29 of password_archivable.rb
`old_passwords_including_cur_change = self.old_passwords.order(:id).reverse_order.limit(self.class.deny_old_passwords).to_a`

I hope someone could apply this patch for Rails 5 as soon as possible.

**Comment by dwmcc** [comment]
+1
Having the same issue with Rails 5 and Devise 4.2.0.

**Comment by ChunAllen** [comment]
+1 Hopefully there will be a fix for this.

**Comment by danielricecodes** [comment]
It looks like there's a workaround.  Just add `password_salt` column to the `old_passwords` table?
