### ISSUE TITLE
DSE does not play well with Konacha, Warden instance is missing

### ISSUE THREAD

**Issue by campbell** [phatworx/devise_security_extension#64]
I am unable to run [Konacha](https://github.com/jfirebaugh/konacha) tests when DSE is installed. It appears that Warden is not being assigned in the request environment and so the Devise signed_in? method fails. Konacha works correctly without DSE installed.

I haven't been able to determine where the Warden instance is initialized for normal RSpec tests, so I cannot try to replicate that with the Konacha task. I have been able to get things running by monkeypatching the #handle_password_change method to first check if the `warden` variable is defined. 

Any help on what I'm missing or need to get this working properly would be appreciated.

```
$ bundle exec rake konacha:run
2013-09-26 16:27:54.015 phantomjs[12890:707] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
NoMethodError: undefined method `authenticate?' for nil:NilClass
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/devise-3.0.0/lib/devise/controllers/helpers.rb:103:in `block in signed_in?'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/devise-3.0.0/lib/devise/controllers/helpers.rb:102:in `each'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/devise-3.0.0/lib/devise/controllers/helpers.rb:102:in `any?'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/devise-3.0.0/lib/devise/controllers/helpers.rb:102:in `signed_in?'
    /Users/campbell/Projects/delightme/config/initializers/devise_security_extension.rb:10:in `block in handle_password_change'
    /Users/campbell/Projects/delightme/config/initializers/devise_security_extension.rb:9:in `each'
    /Users/campbell/Projects/delightme/config/initializers/devise_security_extension.rb:9:in `any?'
    /Users/campbell/Projects/delightme/config/initializers/devise_security_extension.rb:9:in `handle_password_change'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:407:in `_run__446938800661874616__process_action__2153239327820637976__callbacks'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `block in instrument'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `instrument'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/activerecord-3.2.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `block in process_action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:318:in `perform_action_with_newrelic_trace'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:121:in `process'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_controller/metal.rb:203:in `dispatch'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_controller/metal.rb:246:in `block in action'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:36:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:612:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/railties-3.2.13/lib/rails/engine.rb:479:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/rack-1.4.5/lib/rack/builder.rb:134:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in `block in call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `each'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/capybara-2.1.0/lib/capybara/server.rb:19:in `call'
    /Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
    /Users/campbell/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
    /Users/campbell/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /Users/campbell/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
rake aborted!
One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

TypeError: 'undefined' is not an object (evaluating 'window.top.Konacha.getEvents')
TypeError: 'undefined' is not an object (evaluating 'window.top.Konacha.getEvents')
    at phantomjs://webpage.evaluate():1
    at phantomjs://webpage.evaluate():1
    at phantomjs://webpage.evaluate():1
    at phantomjs://webpage.evaluate():1/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/poltergeist-1.4.1/lib/capybara/poltergeist/browser.rb:255:in `command'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/poltergeist-1.4.1/lib/capybara/poltergeist/browser.rb:102:in `evaluate'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/poltergeist-1.4.1/lib/capybara/poltergeist/driver.rb:130:in `evaluate_script'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/capybara-2.1.0/lib/capybara/session.rb:305:in `evaluate_script'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/konacha-3.0.0/lib/konacha/runner.rb:24:in `run'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/konacha-3.0.0/lib/konacha/runner.rb:7:in `start'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/konacha-3.0.0/lib/konacha.rb:21:in `run'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/gems/konacha-3.0.0/lib/tasks/konacha.rake:9:in `block (2 levels) in <top (required)>'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/bin/ruby_noexec_wrapper:14:in `eval'
/Users/campbell/.rvm/gems/ruby-2.0.0-p0@delightme/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => konacha:run
(See full trace by running task with --trace)
```

**Comment by ChristianPeters** [comment]
This issue should be resolved with #146 and can be closed then…?
